In [5]:
import LanusStats as ls

In [29]:
ls.get_available_pages()

dict_keys(['Fbref', 'Sofascore', '365Scores', 'Fotmob'])

In [30]:
ls.get_available_leagues('Fbref')

['Copa de la Liga',
 'Primera Division Argentina',
 'Primera Division Uruguay',
 'Brasileirao',
 'Brasileirao B',
 'Primera Division Colombia',
 'Primera Division Chile',
 'Primera Division Peru',
 'Primera Division Venezuela',
 'Primera Division Ecuador',
 'Primera Division Bolivia',
 'Primera Division Paraguay',
 'Brasileirao F',
 'MLS',
 'USL Championship',
 'Premier League',
 'La Liga',
 'Ligue 1',
 'Bundesliga',
 'Serie A',
 'Big 5 European Leagues']

In [31]:
ls.get_available_season_for_leagues('Fbref' , 'Premier League')

{'id': 9,
 'slug': 'Premier-League',
 'seasons': {'2020-2021', '2021-2022', '2022-2023', '2023-2024'}}

In [7]:
fbref = ls.Fbref()

In [32]:
fbref.possible_stats

['stats',
 'keepers',
 'keepersadv',
 'shooting',
 'passing',
 'passing_types',
 'gca',
 'defense',
 'possession',
 'playingtime',
 'misc']

In [9]:
fbref.get_teams_season_stats('gca', 'Copa de la Liga', season='2024', save_csv=False, stats_vs=False, change_columns_names=False, add_page_name=False)

Starting to scrape teams data from Fbref...

,Squad,# Pl,90s,SCA,SCA90,PassLive,PassDead,TO,Sh,Fld,Def,GCA,GCA90,PassLive,PassDead,TO,Sh,Fld,Def
0,Arg Juniors,26,14.0,314,22.43,232,25,18,15,17,7,43,3.07,29,0,8,1,4,1
1,Atlé Tucumán,24,14.0,355,25.36,232,41,23,23,28,8,15,1.07,12,0,1,2,0,0
2,Banfield,27,14.0,265,18.93,160,46,16,16,18,9,23,1.64,12,2,3,4,2,0
3,Barracas Central,24,14.0,277,19.79,180,31,27,23,12,4,29,2.07,13,3,4,6,2,1
4,Belgrano,33,14.0,272,19.43,177,30,20,20,22,3,35,2.50,16,5,4,4,5,1
5,Boca Juniors,29,14.0,275,19.64,189,28,19,19,15,5,32,2.29,20,1,3,6,2,0
6,Cen. Córdoba–SdE,31,14.0,215,15.36,138,24,24,7,19,3,16,1.14,12,2,1,0,1,0
7,Defensa y Just,30,14.0,318,22.71,216,30,29,18,18,7,30,2.14,18,3,4,3,2,0
8,Deportivo Riestra,30,14.0,191,13.64,120,27,13,5,20,6,16,1.14,11,2,1,0,1,1
9,Estudiantes,29,14.0,394,28.14,288,27,31,26,17,5,33,2.36,24,3,4,1,1,0
10,Gimnasia–LP,26,14.0,336,24.00,230,38,28,18,18,4,30,2.14,18,7,1,0,3,1
11,Godoy Cruz,29,14.0,358,25.57,254,34,20,23,21,6,26,1.86,20,2,1,3,0,0
12,Huracán,25,14.0,331,23.64,228,38,23,16,24,2,23,1.64,17,1,1,1,3,0
13,Independiente,23,14.0,340,24.29,232,41,18,19,23,7,21,1.50,16,2,0,2,1,0
14,Independiente Rivadavia,34,14.0,265,18.93,181,33,16,13,15,7,22,1.57,9,5,2,3,1,2
15,Instituto,25,14.0,322,23.00,211,43,14,27,22,5,28,2.00,15,4,0,4,4,1
16,Lanús,23,14.0,341,24.36,238,41,22,27,11,2,31,2.21,20,2,3,4,2,0
17,Newell's OB,27,14.0,286,20.43,208,25,20,13,19,1,21,1.50,15,1,2,1,2,0
18,Platense,26,14.0,268,19.14,165,42,16,18,18,9,15,1.07,12,0,1,2,0,0
19,Racing Club,28,14.0,346,24.71,258,22,24,16,20,6,43,3.07,30,3,7,3,0,0
20,River Plate,27,14.0,421,30.07,314,26,31,26,18,6,44,3.14,32,4,1,4,3,0
21,Rosario Central,26,14.0,253,18.07,163,42,18,10,18,2,20,1.43,15,1,2,0,2,0
22,San Lorenzo,30,14.0,288,20.57,176,32,25,20,28,7,19,1.36,12,1,0,1,2,3
23,Sarmiento,30,14.0,236,16.86,158,36,15,13,6,8,15,1.07,10,1,2,0,0,2
24,Talleres,28,14.0,377,26.93,255,36,25,27,25,9,43,3.07,24,5,5,4,4,1
25,Tigre,28,14.0,255,18.21,173,26,26,13,12,5,12,0.86,8,0,3,0,1,0
26,Unión,23,14.0,283,20.21,181,40,18,17,24,3,23,1.64,10,4,1,4,4,0
27,Vélez Sarsfield,26,14.0,323,23.07,217,41,21,23,19,2,24,1.71,14,6,0,3,1,0

In [21]:
tabla1 = fbref.get_all_teams_season_stats('Premier League', '2023-2024', save_csv=True, stats_vs=False, change_columns_names=False, add_page_name=False)

Starting to scrape teams data from Fbref...
Starting to scrape teams data from Fbref...
Starting to scrape teams data from Fbref...
Starting to scrape teams data from Fbref...
Starting to scrape teams data from Fbref...
Starting to scrape teams data from Fbref...
Starting to scrape teams data from Fbref...
Starting to scrape teams data from Fbref...
Starting to scrape teams data from Fbref...
Starting to scrape teams data from Fbref...
Starting to scrape teams data from Fbref...

In [16]:
tabla1.columns

Index(['Squad', '# Pl', 'Age', 'Poss', 'MP', 'Starts', 'Min', '90s', 'Gls',
       'Ast',
       ...
       'Crs', 'Int', 'TklW', 'PKwon', 'PKcon', 'OG', 'Recov', 'Won', 'Lost',
       'Won%'],
      dtype='object', length=251)

In [25]:
tabla1 = tabla1.sort_values(by='Won')
tabla1

,Squad,# Pl,Age,Poss,MP,Starts,Min,90s,Gls,Ast,...,Crs,Int,TklW,PKwon,PKcon,OG,Recov,Won,Lost,Won%
12,Manchester City,25,26.6,65.2,38,418,3420,38.0,94,69,...,700,233,305,8,3,1,1734,325,288,53.0
1,Aston Villa,31,26.9,53.1,38,418,3420,38.0,72,55,...,651,236,311,4,2,4,1619,334,363,47.9
17,Tottenham,29,25.2,61.6,38,418,3420,38.0,69,58,...,710,355,451,2,7,3,1907,359,388,48.1
4,Brighton,30,25.9,59.8,38,418,3420,38.0,50,36,...,671,288,366,6,6,2,1751,406,345,54.1
13,Manchester Utd,31,26.1,50.6,38,418,3420,38.0,57,36,...,594,312,408,6,7,1,1850,436,447,49.4
6,Chelsea,32,24.2,58.6,38,418,3420,38.0,76,51,...,558,298,376,11,5,3,1846,440,402,52.3
19,Wolves,27,26.6,48.9,38,418,3420,38.0,47,36,...,578,284,430,4,8,1,1885,441,491,47.3
14,Newcastle Utd,32,27.2,52.2,38,418,3420,38.0,83,55,...,648,284,391,9,5,1,1835,450,418,51.8
9,Fulham,25,28.4,50.6,38,418,3420,38.0,54,40,...,736,371,384,2,8,4,1837,487,509,48.9
0,Arsenal,25,25.0,58.2,38,418,3420,38.0,86,62,...,670,292,348,9,3,1,1752,503,499,50.2
7,Crystal Palace,26,26.7,42.3,38,418,3420,38.0,56,43,...,583,323,464,4,3,2,1909,553,555,49.9
5,Burnley,31,24.5,47.4,38,418,3420,38.0,40,30,...,550,280,342,3,7,3,1727,561,696,44.6
18,West Ham,26,28.3,41.1,38,418,3420,38.0,58,40,...,661,361,426,4,10,4,1817,576,570,50.3
2,Bournemouth,30,25.7,44.4,38,418,3420,38.0,52,39,...,709,357,410,3,7,1,2013,582,671,46.4
10,Liverpool,30,26.3,61.3,38,418,3420,38.0,80,60,...,817,292,418,8,1,2,2034,583,441,56.9
15,Nott'ham Forest,33,25.7,40.6,38,418,3420,38.0,49,43,...,595,331,429,1,4,2,1807,583,556,51.2
16,Sheffield Utd,35,25.7,35.8,38,418,3420,38.0,31,18,...,428,348,405,3,7,7,1638,585,693,45.8
3,Brentford,28,26.6,45.2,38,418,3420,38.0,54,38,...,706,378,399,3,2,0,1892,632,607,51.0
11,Luton Town,28,26.7,42.4,38,418,3420,38.0,49,33,...,841,325,368,2,4,4,1868,635,631,50.2
8,Everton,26,27.1,40.8,38,418,3420,38.0,40,17,...,752,358,442,2,8,3,1970,676,577,54.0

In [28]:
tabla2 = fbref.get_teams_season_stats('gca', 'Premier League', season='2023-2024', save_csv=True, stats_vs=False, change_columns_names=False, add_page_name=False)

Starting to scrape teams data from Fbref...